package com.java.crownlu;
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: train.proto

public final class Train {
  private Train() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface train_ticketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:train_ticket)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 userid = 1;</code>
     */
    boolean hasUserid();
    /**
     * <code>optional int64 userid = 1;</code>
     */
    long getUserid();

    /**
     * <code>optional int32 product_id = 2;</code>
     */
    boolean hasProductId();
    /**
     * <code>optional int32 product_id = 2;</code>
     */
    int getProductId();

    /**
     * <code>optional string src = 3;</code>
     */
    boolean hasSrc();
    /**
     * <code>optional string src = 3;</code>
     */
    String getSrc();
    /**
     * <code>optional string src = 3;</code>
     */
    com.google.protobuf.ByteString
        getSrcBytes();

    /**
     * <code>optional string arrive_next_time = 4;</code>
     */
    boolean hasArriveNextTime();
    /**
     * <code>optional string arrive_next_time = 4;</code>
     */
    String getArriveNextTime();
    /**
     * <code>optional string arrive_next_time = 4;</code>
     */
    com.google.protobuf.ByteString
        getArriveNextTimeBytes();

    /**
     * <code>optional int32 ticket_count = 5;</code>
     */
    boolean hasTicketCount();
    /**
     * <code>optional int32 ticket_count = 5;</code>
     */
    int getTicketCount();

    /**
     * <code>optional double total_price = 6;</code>
     */
    boolean hasTotalPrice();
    /**
     * <code>optional double total_price = 6;</code>
     */
    double getTotalPrice();

    /**
     * <code>optional string seat_type_name = 7;</code>
     */
    boolean hasSeatTypeName();
    /**
     * <code>optional string seat_type_name = 7;</code>
     */
    String getSeatTypeName();
    /**
     * <code>optional string seat_type_name = 7;</code>
     */
    com.google.protobuf.ByteString
        getSeatTypeNameBytes();

    /**
     * <code>optional string next_station = 8;</code>
     */
    boolean hasNextStation();
    /**
     * <code>optional string next_station = 8;</code>
     */
    String getNextStation();
    /**
     * <code>optional string next_station = 8;</code>
     */
    com.google.protobuf.ByteString
        getNextStationBytes();

    /**
     * <code>optional string seat_no = 9;</code>
     */
    boolean hasSeatNo();
    /**
     * <code>optional string seat_no = 9;</code>
     */
    String getSeatNo();
    /**
     * <code>optional string seat_no = 9;</code>
     */
    com.google.protobuf.ByteString
        getSeatNoBytes();

    /**
     * <code>optional string start_time = 10;</code>
     */
    boolean hasStartTime();
    /**
     * <code>optional string start_time = 10;</code>
     */
    String getStartTime();
    /**
     * <code>optional string start_time = 10;</code>
     */
    com.google.protobuf.ByteString
        getStartTimeBytes();

    /**
     * <code>optional int32 display_status = 11;</code>
     */
    boolean hasDisplayStatus();
    /**
     * <code>optional int32 display_status = 11;</code>
     */
    int getDisplayStatus();

    /**
     * <code>optional string coach_no = 12;</code>
     */
    boolean hasCoachNo();
    /**
     * <code>optional string coach_no = 12;</code>
     */
    String getCoachNo();
    /**
     * <code>optional string coach_no = 12;</code>
     */
    com.google.protobuf.ByteString
        getCoachNoBytes();

    /**
     * <code>optional string timetable_url = 13;</code>
     */
    boolean hasTimetableUrl();
    /**
     * <code>optional string timetable_url = 13;</code>
     */
    String getTimetableUrl();
    /**
     * <code>optional string timetable_url = 13;</code>
     */
    com.google.protobuf.ByteString
        getTimetableUrlBytes();

    /**
     * <code>optional string to_station = 14;</code>
     */
    boolean hasToStation();
    /**
     * <code>optional string to_station = 14;</code>
     */
    String getToStation();
    /**
     * <code>optional string to_station = 14;</code>
     */
    com.google.protobuf.ByteString
        getToStationBytes();

    /**
     * <code>optional string train_code = 15;</code>
     */
    boolean hasTrainCode();
    /**
     * <code>optional string train_code = 15;</code>
     */
    String getTrainCode();
    /**
     * <code>optional string train_code = 15;</code>
     */
    com.google.protobuf.ByteString
        getTrainCodeBytes();

    /**
     * <code>optional string from_station = 16;</code>
     */
    boolean hasFromStation();
    /**
     * <code>optional string from_station = 16;</code>
     */
    String getFromStation();
    /**
     * <code>optional string from_station = 16;</code>
     */
    com.google.protobuf.ByteString
        getFromStationBytes();

    /**
     * <code>optional int64 order_id = 17;</code>
     */
    boolean hasOrderId();
    /**
     * <code>optional int64 order_id = 17;</code>
     */
    long getOrderId();

    /**
     * <code>optional string order_url = 18;</code>
     */
    boolean hasOrderUrl();
    /**
     * <code>optional string order_url = 18;</code>
     */
    String getOrderUrl();
    /**
     * <code>optional string order_url = 18;</code>
     */
    com.google.protobuf.ByteString
        getOrderUrlBytes();

    /**
     * <code>optional string arrive_time = 19;</code>
     */
    boolean hasArriveTime();
    /**
     * <code>optional string arrive_time = 19;</code>
     */
    String getArriveTime();
    /**
     * <code>optional string arrive_time = 19;</code>
     */
    com.google.protobuf.ByteString
        getArriveTimeBytes();

    /**
     * <code>optional string send_st = 20;</code>
     */
    boolean hasSendSt();
    /**
     * <code>optional string send_st = 20;</code>
     */
    String getSendSt();
    /**
     * <code>optional string send_st = 20;</code>
     */
    com.google.protobuf.ByteString
        getSendStBytes();
  }
  /**
   * Protobuf type {@code train_ticket}
   */
  public static final class train_ticket extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:train_ticket)
      train_ticketOrBuilder {
    // Use train_ticket.newBuilder() to construct.
    private train_ticket(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private train_ticket(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final train_ticket defaultInstance;
    public static train_ticket getDefaultInstance() {
      return defaultInstance;
    }

    public train_ticket getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private train_ticket(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              userid_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              productId_ = input.readInt32();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              src_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              arriveNextTime_ = bs;
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              ticketCount_ = input.readInt32();
              break;
            }
            case 49: {
              bitField0_ |= 0x00000020;
              totalPrice_ = input.readDouble();
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000040;
              seatTypeName_ = bs;
              break;
            }
            case 66: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000080;
              nextStation_ = bs;
              break;
            }
            case 74: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000100;
              seatNo_ = bs;
              break;
            }
            case 82: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000200;
              startTime_ = bs;
              break;
            }
            case 88: {
              bitField0_ |= 0x00000400;
              displayStatus_ = input.readInt32();
              break;
            }
            case 98: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000800;
              coachNo_ = bs;
              break;
            }
            case 106: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00001000;
              timetableUrl_ = bs;
              break;
            }
            case 114: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00002000;
              toStation_ = bs;
              break;
            }
            case 122: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00004000;
              trainCode_ = bs;
              break;
            }
            case 130: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00008000;
              fromStation_ = bs;
              break;
            }
            case 136: {
              bitField0_ |= 0x00010000;
              orderId_ = input.readInt64();
              break;
            }
            case 146: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00020000;
              orderUrl_ = bs;
              break;
            }
            case 154: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00040000;
              arriveTime_ = bs;
              break;
            }
            case 162: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00080000;
              sendSt_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Train.internal_static_train_ticket_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Train.internal_static_train_ticket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Train.train_ticket.class, Train.train_ticket.Builder.class);
    }

    public static com.google.protobuf.Parser<train_ticket> PARSER =
        new com.google.protobuf.AbstractParser<train_ticket>() {
      public train_ticket parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new train_ticket(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<train_ticket> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int USERID_FIELD_NUMBER = 1;
    private long userid_;
    /**
     * <code>optional int64 userid = 1;</code>
     */
    public boolean hasUserid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 userid = 1;</code>
     */
    public long getUserid() {
      return userid_;
    }

    public static final int PRODUCT_ID_FIELD_NUMBER = 2;
    private int productId_;
    /**
     * <code>optional int32 product_id = 2;</code>
     */
    public boolean hasProductId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 product_id = 2;</code>
     */
    public int getProductId() {
      return productId_;
    }

    public static final int SRC_FIELD_NUMBER = 3;
    private Object src_;
    /**
     * <code>optional string src = 3;</code>
     */
    public boolean hasSrc() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string src = 3;</code>
     */
    public String getSrc() {
      Object ref = src_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          src_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string src = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSrcBytes() {
      Object ref = src_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        src_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ARRIVE_NEXT_TIME_FIELD_NUMBER = 4;
    private Object arriveNextTime_;
    /**
     * <code>optional string arrive_next_time = 4;</code>
     */
    public boolean hasArriveNextTime() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string arrive_next_time = 4;</code>
     */
    public String getArriveNextTime() {
      Object ref = arriveNextTime_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          arriveNextTime_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string arrive_next_time = 4;</code>
     */
    public com.google.protobuf.ByteString
        getArriveNextTimeBytes() {
      Object ref = arriveNextTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        arriveNextTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TICKET_COUNT_FIELD_NUMBER = 5;
    private int ticketCount_;
    /**
     * <code>optional int32 ticket_count = 5;</code>
     */
    public boolean hasTicketCount() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int32 ticket_count = 5;</code>
     */
    public int getTicketCount() {
      return ticketCount_;
    }

    public static final int TOTAL_PRICE_FIELD_NUMBER = 6;
    private double totalPrice_;
    /**
     * <code>optional double total_price = 6;</code>
     */
    public boolean hasTotalPrice() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional double total_price = 6;</code>
     */
    public double getTotalPrice() {
      return totalPrice_;
    }

    public static final int SEAT_TYPE_NAME_FIELD_NUMBER = 7;
    private Object seatTypeName_;
    /**
     * <code>optional string seat_type_name = 7;</code>
     */
    public boolean hasSeatTypeName() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string seat_type_name = 7;</code>
     */
    public String getSeatTypeName() {
      Object ref = seatTypeName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          seatTypeName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string seat_type_name = 7;</code>
     */
    public com.google.protobuf.ByteString
        getSeatTypeNameBytes() {
      Object ref = seatTypeName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        seatTypeName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NEXT_STATION_FIELD_NUMBER = 8;
    private Object nextStation_;
    /**
     * <code>optional string next_station = 8;</code>
     */
    public boolean hasNextStation() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional string next_station = 8;</code>
     */
    public String getNextStation() {
      Object ref = nextStation_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          nextStation_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string next_station = 8;</code>
     */
    public com.google.protobuf.ByteString
        getNextStationBytes() {
      Object ref = nextStation_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        nextStation_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SEAT_NO_FIELD_NUMBER = 9;
    private Object seatNo_;
    /**
     * <code>optional string seat_no = 9;</code>
     */
    public boolean hasSeatNo() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional string seat_no = 9;</code>
     */
    public String getSeatNo() {
      Object ref = seatNo_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          seatNo_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string seat_no = 9;</code>
     */
    public com.google.protobuf.ByteString
        getSeatNoBytes() {
      Object ref = seatNo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        seatNo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int START_TIME_FIELD_NUMBER = 10;
    private Object startTime_;
    /**
     * <code>optional string start_time = 10;</code>
     */
    public boolean hasStartTime() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional string start_time = 10;</code>
     */
    public String getStartTime() {
      Object ref = startTime_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          startTime_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string start_time = 10;</code>
     */
    public com.google.protobuf.ByteString
        getStartTimeBytes() {
      Object ref = startTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        startTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DISPLAY_STATUS_FIELD_NUMBER = 11;
    private int displayStatus_;
    /**
     * <code>optional int32 display_status = 11;</code>
     */
    public boolean hasDisplayStatus() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>optional int32 display_status = 11;</code>
     */
    public int getDisplayStatus() {
      return displayStatus_;
    }

    public static final int COACH_NO_FIELD_NUMBER = 12;
    private Object coachNo_;
    /**
     * <code>optional string coach_no = 12;</code>
     */
    public boolean hasCoachNo() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <code>optional string coach_no = 12;</code>
     */
    public String getCoachNo() {
      Object ref = coachNo_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          coachNo_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string coach_no = 12;</code>
     */
    public com.google.protobuf.ByteString
        getCoachNoBytes() {
      Object ref = coachNo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        coachNo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIMETABLE_URL_FIELD_NUMBER = 13;
    private Object timetableUrl_;
    /**
     * <code>optional string timetable_url = 13;</code>
     */
    public boolean hasTimetableUrl() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    /**
     * <code>optional string timetable_url = 13;</code>
     */
    public String getTimetableUrl() {
      Object ref = timetableUrl_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          timetableUrl_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string timetable_url = 13;</code>
     */
    public com.google.protobuf.ByteString
        getTimetableUrlBytes() {
      Object ref = timetableUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        timetableUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TO_STATION_FIELD_NUMBER = 14;
    private Object toStation_;
    /**
     * <code>optional string to_station = 14;</code>
     */
    public boolean hasToStation() {
      return ((bitField0_ & 0x00002000) == 0x00002000);
    }
    /**
     * <code>optional string to_station = 14;</code>
     */
    public String getToStation() {
      Object ref = toStation_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          toStation_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string to_station = 14;</code>
     */
    public com.google.protobuf.ByteString
        getToStationBytes() {
      Object ref = toStation_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        toStation_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TRAIN_CODE_FIELD_NUMBER = 15;
    private Object trainCode_;
    /**
     * <code>optional string train_code = 15;</code>
     */
    public boolean hasTrainCode() {
      return ((bitField0_ & 0x00004000) == 0x00004000);
    }
    /**
     * <code>optional string train_code = 15;</code>
     */
    public String getTrainCode() {
      Object ref = trainCode_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          trainCode_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string train_code = 15;</code>
     */
    public com.google.protobuf.ByteString
        getTrainCodeBytes() {
      Object ref = trainCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        trainCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FROM_STATION_FIELD_NUMBER = 16;
    private Object fromStation_;
    /**
     * <code>optional string from_station = 16;</code>
     */
    public boolean hasFromStation() {
      return ((bitField0_ & 0x00008000) == 0x00008000);
    }
    /**
     * <code>optional string from_station = 16;</code>
     */
    public String getFromStation() {
      Object ref = fromStation_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          fromStation_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string from_station = 16;</code>
     */
    public com.google.protobuf.ByteString
        getFromStationBytes() {
      Object ref = fromStation_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        fromStation_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ORDER_ID_FIELD_NUMBER = 17;
    private long orderId_;
    /**
     * <code>optional int64 order_id = 17;</code>
     */
    public boolean hasOrderId() {
      return ((bitField0_ & 0x00010000) == 0x00010000);
    }
    /**
     * <code>optional int64 order_id = 17;</code>
     */
    public long getOrderId() {
      return orderId_;
    }

    public static final int ORDER_URL_FIELD_NUMBER = 18;
    private Object orderUrl_;
    /**
     * <code>optional string order_url = 18;</code>
     */
    public boolean hasOrderUrl() {
      return ((bitField0_ & 0x00020000) == 0x00020000);
    }
    /**
     * <code>optional string order_url = 18;</code>
     */
    public String getOrderUrl() {
      Object ref = orderUrl_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          orderUrl_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string order_url = 18;</code>
     */
    public com.google.protobuf.ByteString
        getOrderUrlBytes() {
      Object ref = orderUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        orderUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ARRIVE_TIME_FIELD_NUMBER = 19;
    private Object arriveTime_;
    /**
     * <code>optional string arrive_time = 19;</code>
     */
    public boolean hasArriveTime() {
      return ((bitField0_ & 0x00040000) == 0x00040000);
    }
    /**
     * <code>optional string arrive_time = 19;</code>
     */
    public String getArriveTime() {
      Object ref = arriveTime_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          arriveTime_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string arrive_time = 19;</code>
     */
    public com.google.protobuf.ByteString
        getArriveTimeBytes() {
      Object ref = arriveTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        arriveTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SEND_ST_FIELD_NUMBER = 20;
    private Object sendSt_;
    /**
     * <code>optional string send_st = 20;</code>
     */
    public boolean hasSendSt() {
      return ((bitField0_ & 0x00080000) == 0x00080000);
    }
    /**
     * <code>optional string send_st = 20;</code>
     */
    public String getSendSt() {
      Object ref = sendSt_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sendSt_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string send_st = 20;</code>
     */
    public com.google.protobuf.ByteString
        getSendStBytes() {
      Object ref = sendSt_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        sendSt_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      userid_ = 0L;
      productId_ = 0;
      src_ = "";
      arriveNextTime_ = "";
      ticketCount_ = 0;
      totalPrice_ = 0D;
      seatTypeName_ = "";
      nextStation_ = "";
      seatNo_ = "";
      startTime_ = "";
      displayStatus_ = 0;
      coachNo_ = "";
      timetableUrl_ = "";
      toStation_ = "";
      trainCode_ = "";
      fromStation_ = "";
      orderId_ = 0L;
      orderUrl_ = "";
      arriveTime_ = "";
      sendSt_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, userid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, productId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getSrcBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getArriveNextTimeBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, ticketCount_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeDouble(6, totalPrice_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getSeatTypeNameBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, getNextStationBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(9, getSeatNoBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeBytes(10, getStartTimeBytes());
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeInt32(11, displayStatus_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeBytes(12, getCoachNoBytes());
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        output.writeBytes(13, getTimetableUrlBytes());
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        output.writeBytes(14, getToStationBytes());
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        output.writeBytes(15, getTrainCodeBytes());
      }
      if (((bitField0_ & 0x00008000) == 0x00008000)) {
        output.writeBytes(16, getFromStationBytes());
      }
      if (((bitField0_ & 0x00010000) == 0x00010000)) {
        output.writeInt64(17, orderId_);
      }
      if (((bitField0_ & 0x00020000) == 0x00020000)) {
        output.writeBytes(18, getOrderUrlBytes());
      }
      if (((bitField0_ & 0x00040000) == 0x00040000)) {
        output.writeBytes(19, getArriveTimeBytes());
      }
      if (((bitField0_ & 0x00080000) == 0x00080000)) {
        output.writeBytes(20, getSendStBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, userid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, productId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getSrcBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getArriveNextTimeBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, ticketCount_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(6, totalPrice_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getSeatTypeNameBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getNextStationBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, getSeatNoBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(10, getStartTimeBytes());
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(11, displayStatus_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(12, getCoachNoBytes());
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(13, getTimetableUrlBytes());
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(14, getToStationBytes());
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(15, getTrainCodeBytes());
      }
      if (((bitField0_ & 0x00008000) == 0x00008000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(16, getFromStationBytes());
      }
      if (((bitField0_ & 0x00010000) == 0x00010000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(17, orderId_);
      }
      if (((bitField0_ & 0x00020000) == 0x00020000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(18, getOrderUrlBytes());
      }
      if (((bitField0_ & 0x00040000) == 0x00040000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(19, getArriveTimeBytes());
      }
      if (((bitField0_ & 0x00080000) == 0x00080000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(20, getSendStBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Train.train_ticket parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Train.train_ticket parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Train.train_ticket parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Train.train_ticket parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Train.train_ticket parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Train.train_ticket parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Train.train_ticket parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Train.train_ticket parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Train.train_ticket parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Train.train_ticket parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Train.train_ticket prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code train_ticket}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:train_ticket)
        Train.train_ticketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Train.internal_static_train_ticket_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Train.internal_static_train_ticket_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Train.train_ticket.class, Train.train_ticket.Builder.class);
      }

      // Construct using Train.train_ticket.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        userid_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        productId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        src_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        arriveNextTime_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        ticketCount_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        totalPrice_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000020);
        seatTypeName_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        nextStation_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        seatNo_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        startTime_ = "";
        bitField0_ = (bitField0_ & ~0x00000200);
        displayStatus_ = 0;
        bitField0_ = (bitField0_ & ~0x00000400);
        coachNo_ = "";
        bitField0_ = (bitField0_ & ~0x00000800);
        timetableUrl_ = "";
        bitField0_ = (bitField0_ & ~0x00001000);
        toStation_ = "";
        bitField0_ = (bitField0_ & ~0x00002000);
        trainCode_ = "";
        bitField0_ = (bitField0_ & ~0x00004000);
        fromStation_ = "";
        bitField0_ = (bitField0_ & ~0x00008000);
        orderId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00010000);
        orderUrl_ = "";
        bitField0_ = (bitField0_ & ~0x00020000);
        arriveTime_ = "";
        bitField0_ = (bitField0_ & ~0x00040000);
        sendSt_ = "";
        bitField0_ = (bitField0_ & ~0x00080000);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Train.internal_static_train_ticket_descriptor;
      }

      public Train.train_ticket getDefaultInstanceForType() {
        return Train.train_ticket.getDefaultInstance();
      }

      public Train.train_ticket build() {
        Train.train_ticket result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Train.train_ticket buildPartial() {
        Train.train_ticket result = new Train.train_ticket(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userid_ = userid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.productId_ = productId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.src_ = src_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.arriveNextTime_ = arriveNextTime_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.ticketCount_ = ticketCount_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.totalPrice_ = totalPrice_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.seatTypeName_ = seatTypeName_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.nextStation_ = nextStation_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.seatNo_ = seatNo_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.startTime_ = startTime_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.displayStatus_ = displayStatus_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.coachNo_ = coachNo_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00001000;
        }
        result.timetableUrl_ = timetableUrl_;
        if (((from_bitField0_ & 0x00002000) == 0x00002000)) {
          to_bitField0_ |= 0x00002000;
        }
        result.toStation_ = toStation_;
        if (((from_bitField0_ & 0x00004000) == 0x00004000)) {
          to_bitField0_ |= 0x00004000;
        }
        result.trainCode_ = trainCode_;
        if (((from_bitField0_ & 0x00008000) == 0x00008000)) {
          to_bitField0_ |= 0x00008000;
        }
        result.fromStation_ = fromStation_;
        if (((from_bitField0_ & 0x00010000) == 0x00010000)) {
          to_bitField0_ |= 0x00010000;
        }
        result.orderId_ = orderId_;
        if (((from_bitField0_ & 0x00020000) == 0x00020000)) {
          to_bitField0_ |= 0x00020000;
        }
        result.orderUrl_ = orderUrl_;
        if (((from_bitField0_ & 0x00040000) == 0x00040000)) {
          to_bitField0_ |= 0x00040000;
        }
        result.arriveTime_ = arriveTime_;
        if (((from_bitField0_ & 0x00080000) == 0x00080000)) {
          to_bitField0_ |= 0x00080000;
        }
        result.sendSt_ = sendSt_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Train.train_ticket) {
          return mergeFrom((Train.train_ticket)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Train.train_ticket other) {
        if (other == Train.train_ticket.getDefaultInstance()) return this;
        if (other.hasUserid()) {
          setUserid(other.getUserid());
        }
        if (other.hasProductId()) {
          setProductId(other.getProductId());
        }
        if (other.hasSrc()) {
          bitField0_ |= 0x00000004;
          src_ = other.src_;
          onChanged();
        }
        if (other.hasArriveNextTime()) {
          bitField0_ |= 0x00000008;
          arriveNextTime_ = other.arriveNextTime_;
          onChanged();
        }
        if (other.hasTicketCount()) {
          setTicketCount(other.getTicketCount());
        }
        if (other.hasTotalPrice()) {
          setTotalPrice(other.getTotalPrice());
        }
        if (other.hasSeatTypeName()) {
          bitField0_ |= 0x00000040;
          seatTypeName_ = other.seatTypeName_;
          onChanged();
        }
        if (other.hasNextStation()) {
          bitField0_ |= 0x00000080;
          nextStation_ = other.nextStation_;
          onChanged();
        }
        if (other.hasSeatNo()) {
          bitField0_ |= 0x00000100;
          seatNo_ = other.seatNo_;
          onChanged();
        }
        if (other.hasStartTime()) {
          bitField0_ |= 0x00000200;
          startTime_ = other.startTime_;
          onChanged();
        }
        if (other.hasDisplayStatus()) {
          setDisplayStatus(other.getDisplayStatus());
        }
        if (other.hasCoachNo()) {
          bitField0_ |= 0x00000800;
          coachNo_ = other.coachNo_;
          onChanged();
        }
        if (other.hasTimetableUrl()) {
          bitField0_ |= 0x00001000;
          timetableUrl_ = other.timetableUrl_;
          onChanged();
        }
        if (other.hasToStation()) {
          bitField0_ |= 0x00002000;
          toStation_ = other.toStation_;
          onChanged();
        }
        if (other.hasTrainCode()) {
          bitField0_ |= 0x00004000;
          trainCode_ = other.trainCode_;
          onChanged();
        }
        if (other.hasFromStation()) {
          bitField0_ |= 0x00008000;
          fromStation_ = other.fromStation_;
          onChanged();
        }
        if (other.hasOrderId()) {
          setOrderId(other.getOrderId());
        }
        if (other.hasOrderUrl()) {
          bitField0_ |= 0x00020000;
          orderUrl_ = other.orderUrl_;
          onChanged();
        }
        if (other.hasArriveTime()) {
          bitField0_ |= 0x00040000;
          arriveTime_ = other.arriveTime_;
          onChanged();
        }
        if (other.hasSendSt()) {
          bitField0_ |= 0x00080000;
          sendSt_ = other.sendSt_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Train.train_ticket parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Train.train_ticket) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long userid_ ;
      /**
       * <code>optional int64 userid = 1;</code>
       */
      public boolean hasUserid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 userid = 1;</code>
       */
      public long getUserid() {
        return userid_;
      }
      /**
       * <code>optional int64 userid = 1;</code>
       */
      public Builder setUserid(long value) {
        bitField0_ |= 0x00000001;
        userid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 userid = 1;</code>
       */
      public Builder clearUserid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userid_ = 0L;
        onChanged();
        return this;
      }

      private int productId_ ;
      /**
       * <code>optional int32 product_id = 2;</code>
       */
      public boolean hasProductId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 product_id = 2;</code>
       */
      public int getProductId() {
        return productId_;
      }
      /**
       * <code>optional int32 product_id = 2;</code>
       */
      public Builder setProductId(int value) {
        bitField0_ |= 0x00000002;
        productId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 product_id = 2;</code>
       */
      public Builder clearProductId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        productId_ = 0;
        onChanged();
        return this;
      }

      private Object src_ = "";
      /**
       * <code>optional string src = 3;</code>
       */
      public boolean hasSrc() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string src = 3;</code>
       */
      public String getSrc() {
        Object ref = src_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            src_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string src = 3;</code>
       */
      public com.google.protobuf.ByteString
          getSrcBytes() {
        Object ref = src_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          src_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string src = 3;</code>
       */
      public Builder setSrc(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        src_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string src = 3;</code>
       */
      public Builder clearSrc() {
        bitField0_ = (bitField0_ & ~0x00000004);
        src_ = getDefaultInstance().getSrc();
        onChanged();
        return this;
      }
      /**
       * <code>optional string src = 3;</code>
       */
      public Builder setSrcBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        src_ = value;
        onChanged();
        return this;
      }

      private Object arriveNextTime_ = "";
      /**
       * <code>optional string arrive_next_time = 4;</code>
       */
      public boolean hasArriveNextTime() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string arrive_next_time = 4;</code>
       */
      public String getArriveNextTime() {
        Object ref = arriveNextTime_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            arriveNextTime_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string arrive_next_time = 4;</code>
       */
      public com.google.protobuf.ByteString
          getArriveNextTimeBytes() {
        Object ref = arriveNextTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          arriveNextTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string arrive_next_time = 4;</code>
       */
      public Builder setArriveNextTime(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        arriveNextTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string arrive_next_time = 4;</code>
       */
      public Builder clearArriveNextTime() {
        bitField0_ = (bitField0_ & ~0x00000008);
        arriveNextTime_ = getDefaultInstance().getArriveNextTime();
        onChanged();
        return this;
      }
      /**
       * <code>optional string arrive_next_time = 4;</code>
       */
      public Builder setArriveNextTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        arriveNextTime_ = value;
        onChanged();
        return this;
      }

      private int ticketCount_ ;
      /**
       * <code>optional int32 ticket_count = 5;</code>
       */
      public boolean hasTicketCount() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 ticket_count = 5;</code>
       */
      public int getTicketCount() {
        return ticketCount_;
      }
      /**
       * <code>optional int32 ticket_count = 5;</code>
       */
      public Builder setTicketCount(int value) {
        bitField0_ |= 0x00000010;
        ticketCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 ticket_count = 5;</code>
       */
      public Builder clearTicketCount() {
        bitField0_ = (bitField0_ & ~0x00000010);
        ticketCount_ = 0;
        onChanged();
        return this;
      }

      private double totalPrice_ ;
      /**
       * <code>optional double total_price = 6;</code>
       */
      public boolean hasTotalPrice() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional double total_price = 6;</code>
       */
      public double getTotalPrice() {
        return totalPrice_;
      }
      /**
       * <code>optional double total_price = 6;</code>
       */
      public Builder setTotalPrice(double value) {
        bitField0_ |= 0x00000020;
        totalPrice_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double total_price = 6;</code>
       */
      public Builder clearTotalPrice() {
        bitField0_ = (bitField0_ & ~0x00000020);
        totalPrice_ = 0D;
        onChanged();
        return this;
      }

      private Object seatTypeName_ = "";
      /**
       * <code>optional string seat_type_name = 7;</code>
       */
      public boolean hasSeatTypeName() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional string seat_type_name = 7;</code>
       */
      public String getSeatTypeName() {
        Object ref = seatTypeName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            seatTypeName_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string seat_type_name = 7;</code>
       */
      public com.google.protobuf.ByteString
          getSeatTypeNameBytes() {
        Object ref = seatTypeName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          seatTypeName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string seat_type_name = 7;</code>
       */
      public Builder setSeatTypeName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        seatTypeName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string seat_type_name = 7;</code>
       */
      public Builder clearSeatTypeName() {
        bitField0_ = (bitField0_ & ~0x00000040);
        seatTypeName_ = getDefaultInstance().getSeatTypeName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string seat_type_name = 7;</code>
       */
      public Builder setSeatTypeNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        seatTypeName_ = value;
        onChanged();
        return this;
      }

      private Object nextStation_ = "";
      /**
       * <code>optional string next_station = 8;</code>
       */
      public boolean hasNextStation() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional string next_station = 8;</code>
       */
      public String getNextStation() {
        Object ref = nextStation_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            nextStation_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string next_station = 8;</code>
       */
      public com.google.protobuf.ByteString
          getNextStationBytes() {
        Object ref = nextStation_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          nextStation_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string next_station = 8;</code>
       */
      public Builder setNextStation(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        nextStation_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string next_station = 8;</code>
       */
      public Builder clearNextStation() {
        bitField0_ = (bitField0_ & ~0x00000080);
        nextStation_ = getDefaultInstance().getNextStation();
        onChanged();
        return this;
      }
      /**
       * <code>optional string next_station = 8;</code>
       */
      public Builder setNextStationBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        nextStation_ = value;
        onChanged();
        return this;
      }

      private Object seatNo_ = "";
      /**
       * <code>optional string seat_no = 9;</code>
       */
      public boolean hasSeatNo() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional string seat_no = 9;</code>
       */
      public String getSeatNo() {
        Object ref = seatNo_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            seatNo_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string seat_no = 9;</code>
       */
      public com.google.protobuf.ByteString
          getSeatNoBytes() {
        Object ref = seatNo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          seatNo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string seat_no = 9;</code>
       */
      public Builder setSeatNo(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        seatNo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string seat_no = 9;</code>
       */
      public Builder clearSeatNo() {
        bitField0_ = (bitField0_ & ~0x00000100);
        seatNo_ = getDefaultInstance().getSeatNo();
        onChanged();
        return this;
      }
      /**
       * <code>optional string seat_no = 9;</code>
       */
      public Builder setSeatNoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        seatNo_ = value;
        onChanged();
        return this;
      }

      private Object startTime_ = "";
      /**
       * <code>optional string start_time = 10;</code>
       */
      public boolean hasStartTime() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional string start_time = 10;</code>
       */
      public String getStartTime() {
        Object ref = startTime_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            startTime_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string start_time = 10;</code>
       */
      public com.google.protobuf.ByteString
          getStartTimeBytes() {
        Object ref = startTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          startTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string start_time = 10;</code>
       */
      public Builder setStartTime(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        startTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string start_time = 10;</code>
       */
      public Builder clearStartTime() {
        bitField0_ = (bitField0_ & ~0x00000200);
        startTime_ = getDefaultInstance().getStartTime();
        onChanged();
        return this;
      }
      /**
       * <code>optional string start_time = 10;</code>
       */
      public Builder setStartTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        startTime_ = value;
        onChanged();
        return this;
      }

      private int displayStatus_ ;
      /**
       * <code>optional int32 display_status = 11;</code>
       */
      public boolean hasDisplayStatus() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>optional int32 display_status = 11;</code>
       */
      public int getDisplayStatus() {
        return displayStatus_;
      }
      /**
       * <code>optional int32 display_status = 11;</code>
       */
      public Builder setDisplayStatus(int value) {
        bitField0_ |= 0x00000400;
        displayStatus_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 display_status = 11;</code>
       */
      public Builder clearDisplayStatus() {
        bitField0_ = (bitField0_ & ~0x00000400);
        displayStatus_ = 0;
        onChanged();
        return this;
      }

      private Object coachNo_ = "";
      /**
       * <code>optional string coach_no = 12;</code>
       */
      public boolean hasCoachNo() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <code>optional string coach_no = 12;</code>
       */
      public String getCoachNo() {
        Object ref = coachNo_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            coachNo_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string coach_no = 12;</code>
       */
      public com.google.protobuf.ByteString
          getCoachNoBytes() {
        Object ref = coachNo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          coachNo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string coach_no = 12;</code>
       */
      public Builder setCoachNo(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000800;
        coachNo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string coach_no = 12;</code>
       */
      public Builder clearCoachNo() {
        bitField0_ = (bitField0_ & ~0x00000800);
        coachNo_ = getDefaultInstance().getCoachNo();
        onChanged();
        return this;
      }
      /**
       * <code>optional string coach_no = 12;</code>
       */
      public Builder setCoachNoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000800;
        coachNo_ = value;
        onChanged();
        return this;
      }

      private Object timetableUrl_ = "";
      /**
       * <code>optional string timetable_url = 13;</code>
       */
      public boolean hasTimetableUrl() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      /**
       * <code>optional string timetable_url = 13;</code>
       */
      public String getTimetableUrl() {
        Object ref = timetableUrl_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            timetableUrl_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string timetable_url = 13;</code>
       */
      public com.google.protobuf.ByteString
          getTimetableUrlBytes() {
        Object ref = timetableUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          timetableUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string timetable_url = 13;</code>
       */
      public Builder setTimetableUrl(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00001000;
        timetableUrl_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string timetable_url = 13;</code>
       */
      public Builder clearTimetableUrl() {
        bitField0_ = (bitField0_ & ~0x00001000);
        timetableUrl_ = getDefaultInstance().getTimetableUrl();
        onChanged();
        return this;
      }
      /**
       * <code>optional string timetable_url = 13;</code>
       */
      public Builder setTimetableUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00001000;
        timetableUrl_ = value;
        onChanged();
        return this;
      }

      private Object toStation_ = "";
      /**
       * <code>optional string to_station = 14;</code>
       */
      public boolean hasToStation() {
        return ((bitField0_ & 0x00002000) == 0x00002000);
      }
      /**
       * <code>optional string to_station = 14;</code>
       */
      public String getToStation() {
        Object ref = toStation_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            toStation_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string to_station = 14;</code>
       */
      public com.google.protobuf.ByteString
          getToStationBytes() {
        Object ref = toStation_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          toStation_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string to_station = 14;</code>
       */
      public Builder setToStation(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00002000;
        toStation_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string to_station = 14;</code>
       */
      public Builder clearToStation() {
        bitField0_ = (bitField0_ & ~0x00002000);
        toStation_ = getDefaultInstance().getToStation();
        onChanged();
        return this;
      }
      /**
       * <code>optional string to_station = 14;</code>
       */
      public Builder setToStationBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00002000;
        toStation_ = value;
        onChanged();
        return this;
      }

      private Object trainCode_ = "";
      /**
       * <code>optional string train_code = 15;</code>
       */
      public boolean hasTrainCode() {
        return ((bitField0_ & 0x00004000) == 0x00004000);
      }
      /**
       * <code>optional string train_code = 15;</code>
       */
      public String getTrainCode() {
        Object ref = trainCode_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            trainCode_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string train_code = 15;</code>
       */
      public com.google.protobuf.ByteString
          getTrainCodeBytes() {
        Object ref = trainCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          trainCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string train_code = 15;</code>
       */
      public Builder setTrainCode(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00004000;
        trainCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string train_code = 15;</code>
       */
      public Builder clearTrainCode() {
        bitField0_ = (bitField0_ & ~0x00004000);
        trainCode_ = getDefaultInstance().getTrainCode();
        onChanged();
        return this;
      }
      /**
       * <code>optional string train_code = 15;</code>
       */
      public Builder setTrainCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00004000;
        trainCode_ = value;
        onChanged();
        return this;
      }

      private Object fromStation_ = "";
      /**
       * <code>optional string from_station = 16;</code>
       */
      public boolean hasFromStation() {
        return ((bitField0_ & 0x00008000) == 0x00008000);
      }
      /**
       * <code>optional string from_station = 16;</code>
       */
      public String getFromStation() {
        Object ref = fromStation_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            fromStation_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string from_station = 16;</code>
       */
      public com.google.protobuf.ByteString
          getFromStationBytes() {
        Object ref = fromStation_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          fromStation_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string from_station = 16;</code>
       */
      public Builder setFromStation(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00008000;
        fromStation_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string from_station = 16;</code>
       */
      public Builder clearFromStation() {
        bitField0_ = (bitField0_ & ~0x00008000);
        fromStation_ = getDefaultInstance().getFromStation();
        onChanged();
        return this;
      }
      /**
       * <code>optional string from_station = 16;</code>
       */
      public Builder setFromStationBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00008000;
        fromStation_ = value;
        onChanged();
        return this;
      }

      private long orderId_ ;
      /**
       * <code>optional int64 order_id = 17;</code>
       */
      public boolean hasOrderId() {
        return ((bitField0_ & 0x00010000) == 0x00010000);
      }
      /**
       * <code>optional int64 order_id = 17;</code>
       */
      public long getOrderId() {
        return orderId_;
      }
      /**
       * <code>optional int64 order_id = 17;</code>
       */
      public Builder setOrderId(long value) {
        bitField0_ |= 0x00010000;
        orderId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 order_id = 17;</code>
       */
      public Builder clearOrderId() {
        bitField0_ = (bitField0_ & ~0x00010000);
        orderId_ = 0L;
        onChanged();
        return this;
      }

      private Object orderUrl_ = "";
      /**
       * <code>optional string order_url = 18;</code>
       */
      public boolean hasOrderUrl() {
        return ((bitField0_ & 0x00020000) == 0x00020000);
      }
      /**
       * <code>optional string order_url = 18;</code>
       */
      public String getOrderUrl() {
        Object ref = orderUrl_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            orderUrl_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string order_url = 18;</code>
       */
      public com.google.protobuf.ByteString
          getOrderUrlBytes() {
        Object ref = orderUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          orderUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string order_url = 18;</code>
       */
      public Builder setOrderUrl(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00020000;
        orderUrl_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string order_url = 18;</code>
       */
      public Builder clearOrderUrl() {
        bitField0_ = (bitField0_ & ~0x00020000);
        orderUrl_ = getDefaultInstance().getOrderUrl();
        onChanged();
        return this;
      }
      /**
       * <code>optional string order_url = 18;</code>
       */
      public Builder setOrderUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00020000;
        orderUrl_ = value;
        onChanged();
        return this;
      }

      private Object arriveTime_ = "";
      /**
       * <code>optional string arrive_time = 19;</code>
       */
      public boolean hasArriveTime() {
        return ((bitField0_ & 0x00040000) == 0x00040000);
      }
      /**
       * <code>optional string arrive_time = 19;</code>
       */
      public String getArriveTime() {
        Object ref = arriveTime_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            arriveTime_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string arrive_time = 19;</code>
       */
      public com.google.protobuf.ByteString
          getArriveTimeBytes() {
        Object ref = arriveTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          arriveTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string arrive_time = 19;</code>
       */
      public Builder setArriveTime(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00040000;
        arriveTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string arrive_time = 19;</code>
       */
      public Builder clearArriveTime() {
        bitField0_ = (bitField0_ & ~0x00040000);
        arriveTime_ = getDefaultInstance().getArriveTime();
        onChanged();
        return this;
      }
      /**
       * <code>optional string arrive_time = 19;</code>
       */
      public Builder setArriveTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00040000;
        arriveTime_ = value;
        onChanged();
        return this;
      }

      private Object sendSt_ = "";
      /**
       * <code>optional string send_st = 20;</code>
       */
      public boolean hasSendSt() {
        return ((bitField0_ & 0x00080000) == 0x00080000);
      }
      /**
       * <code>optional string send_st = 20;</code>
       */
      public String getSendSt() {
        Object ref = sendSt_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            sendSt_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string send_st = 20;</code>
       */
      public com.google.protobuf.ByteString
          getSendStBytes() {
        Object ref = sendSt_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          sendSt_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string send_st = 20;</code>
       */
      public Builder setSendSt(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00080000;
        sendSt_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string send_st = 20;</code>
       */
      public Builder clearSendSt() {
        bitField0_ = (bitField0_ & ~0x00080000);
        sendSt_ = getDefaultInstance().getSendSt();
        onChanged();
        return this;
      }
      /**
       * <code>optional string send_st = 20;</code>
       */
      public Builder setSendStBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00080000;
        sendSt_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:train_ticket)
    }

    static {
      defaultInstance = new train_ticket(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:train_ticket)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_train_ticket_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_train_ticket_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\013train.proto\"\241\003\n\014train_ticket\022\016\n\006userid" +
      "\030\001 \001(\003\022\022\n\nproduct_id\030\002 \001(\005\022\013\n\003src\030\003 \001(\t\022" +
      "\030\n\020arrive_next_time\030\004 \001(\t\022\024\n\014ticket_coun" +
      "t\030\005 \001(\005\022\023\n\013total_price\030\006 \001(\001\022\026\n\016seat_typ" +
      "e_name\030\007 \001(\t\022\024\n\014next_station\030\010 \001(\t\022\017\n\007se" +
      "at_no\030\t \001(\t\022\022\n\nstart_time\030\n \001(\t\022\026\n\016displ" +
      "ay_status\030\013 \001(\005\022\020\n\010coach_no\030\014 \001(\t\022\025\n\rtim" +
      "etable_url\030\r \001(\t\022\022\n\nto_station\030\016 \001(\t\022\022\n\n" +
      "train_code\030\017 \001(\t\022\024\n\014from_station\030\020 \001(\t\022\020" +
      "\n\010order_id\030\021 \001(\003\022\021\n\torder_url\030\022 \001(\t\022\023\n\013a",
      "rrive_time\030\023 \001(\t\022\017\n\007send_st\030\024 \001(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_train_ticket_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_train_ticket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_train_ticket_descriptor,
        new String[] { "Userid", "ProductId", "Src", "ArriveNextTime", "TicketCount", "TotalPrice", "SeatTypeName", "NextStation", "SeatNo", "StartTime", "DisplayStatus", "CoachNo", "TimetableUrl", "ToStation", "TrainCode", "FromStation", "OrderId", "OrderUrl", "ArriveTime", "SendSt", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
